

\newpage 
# {-}

\  

\  
\vfill
\  

\  

----------------------------------------------------------------------------------------------------------------------
    Η εργασία αυτή διανέμεται υπό την άδεια:
    **Creative Commons - Αναφορά Δημιουργού -**
    **Μη Εμπορική Χρήση - Παρόμοια Διανομή 4.0 Διεθνές.**
    [http://creativecommons.org/licenses/by-nc-sa/4.0/](http://creativecommons.org/licenses/by-nc-sa/4.0/)
----------------------------------------------------------------------------------------------------------------------

\  
\vfill \  
\  

<!-- -------------------------------------------------------------------------------------------------------------------- -->
<!--    Για διορθώσεις και προσθήκες επικοινωνήστε με Thanasisn [github.com/thanasisn](https://github.com/thanasisn). -->
<!-- -------------------------------------------------------------------------------------------------------------------- -->

\  
\vfill \  
\  

**_Σημείωση:_ Ο πηγαίος κώδικας (source code) που παρατίθεται εδώ είναι ένα παράδειγμα εφαρμογής κάποιων τεχνικών. Σε περίπτωση που θέλετε να τον χρησιμοποιήσετε, προτείνουμε να δοκιμαστεί η καταλληλότητα του για την επιθυμητή χρήση, πρώτα σε μη σημαντικές εφαρμογές (non-critical). Τα παραδείγματα κώδικα εδώ, διαφέρουν από αυτά που χρησιμοποιούμε, λόγω της συνεχής εξέλιξης και βελτίωσης κατά την χρήση τους.**




\newpage

\ \
\vfill
\ \

# Εισαγωγή. {-#intro}

Το παρόν είναι ένας ανεπίσημος οδηγός για τη χρήση και τη λειτουργία του ηλιοστάτη του ΕΦΑ. Συντάχτηκε από της διαθέσιμες πληροφορίες για τον ηλιοστάτη καθώς και από την εμπειρία που αποκομίσαμε κατά τη χρήση του. Σκοπός μας είναι να βοηθήσει στην περαιτέρω ανάπτυξη και χρήση του, γι' αυτό ζητούμε την συνεισφορά σας στη βελτίωσή του. Για διορθώσεις και προσθήκες μπορείτε να επικοινωνήσετε με τον [Νάτση  Αθανάσιο](mailto:natsisthanasis@gmail.com) (natsisthanasis@gmail.com) ή το Εργαστήριο Φυσικής της Ατμόσφαιρας του Α.Π.Θ.

\ \
\vfill
\ \
