\newpage

`r if( knitr:::is_latex_output()) '\\appendix'`
`r if(!knitr:::is_latex_output()) '# (APPENDIX) Appendix {-#appendix}'`


CHP-1 Quick startup (on 'radmon' computer).
===========================================

<!-- \vspace{-1.5\baselineskip}  -->
Σύνδεση του tracker. {-}
------------------------
\vspace{-0.6\baselineskip}

Στο τροφοδοτικό του tracker συνδέονται τρία καλώδια.
Συνήθως, η σύνδεση πετυχαίνει αν τα καλώδια συνδεθούν με τη σειρά από δεξιά προς τα αριστερά ή το αντίθετο.
Η εκτέλεση του προγράμματος θα δείξει αν η επικοινωνία μπορεί να γίνει σωστά.

\vspace{-1.05\baselineskip}
Reset tracker. {-}
-------------------
\vspace{-0.6\baselineskip}

Όταν ο tracker τροφοδοτείται τα ηλεκτρονικά του είναι ενεργά, μερικές φορές, αυτό αποτρέπει την επανασύνδεση.
Για να λυθεί αυτό ή πρέπει να μείνει για μερικά λεπτά χωρίς τροφοδοσία, ή να βραχυκυκλωθούν οι επαφές που τροφοδοτούν την ηλεκτρονική πλακέτα του tracker.
**ΠΡΟΣΟΧΗ: εφαρμόστε λογική και αποσυνδέστε πρώτα την τροφοδοσία ρεύματος**.
Αν το περίβλημα του tracker είναι ανοικτό, οι επαφές είναι προσβάσιμες. Εναλλακτικά, μπορούν να βραχυκυκλωθούν οι επαφές του καλωδίου με κάποιο μεταλλικό αντικείμενο και μόνο από τη μεριά του καλωδίου που συνδέεται στο τροφοδοτικό, ώστε να είστε σίγουροι για τη κατάσταση τροφοδοσίας.

\vspace{-1.05\baselineskip}
Εκκίνηση του προγράμματος ελέγχου {-}
-------------------------------------
\vspace{-0.6\baselineskip}

Το πρόγραμμα ελέγχου του tracker (**sun_tracker_main.py**) μπορεί να ξεκινήσει:

* Χειροκίνητα (link στην επιφάνεια εργασίας)
* Μέσω του 'Scheduled Tasks' (properties -\> run)
* Εκτέλεση από command line (cmd.exe):
```{bash eval=F}
c:\><python path>\python.exe <script path>\sun_tracker_main.py
```


\vspace{-1.05\baselineskip}
Διόπτευση (sighting) {-}
-------------------------
\vspace{-0.6\baselineskip}

Το sighting του Ήλιου μπορεί να γίνει με το πρόγραμμα **tracker_sighting_no_ui_tcp-port.py** (υπάρχει link στην επιφάνεια εργασίας).
Το πρόγραμμα εμφανίζει τις δυνατές επιλογές στην οθόνη και περιμένει είσοδο από το πληκτρολόγιο.
Οι ρυθμίσεις επιδρούν άμεσα στη θέση του tracker (το πρόγραμμα **sun_tracker_main.py** πρέπει να εκτελείται και ο tracker πρέπει να έχει αρχίσει την κανονική λειτουργία).
Ανάδραση (feedback) των ρυθμίσεων μπορούμε να έχουμε παρακολουθώντας το terminal που τρέχει το **sun_tracker_main.py**. **ΠΡΟΣΟΧΗ.** Οι ρυθμίσεις πρέπει να σωθούν (`'s'`) για να αποθηκευτούν στον δίσκο και να διατηρηθούν στην επόμενη εκτέλεση (ημέρα).

**Σημείωση:** Είναι βολικό το sighting να γίνεται με κάποιο smart phone μέσω remote desktop ('rdp').
Έτσι, μπορεί να υπάρχει άμεση επίβλεψη της κίνησης του tracker και των διορθώσεων και διευκολύνεται ο συγχρονισμός της κίνησης του tracker με τη θέση του ήλιου.

\vspace{-1.05\baselineskip}
Σύνδεση πολυμέτρου 'Protek 506' {-}
--------------------------------------------------------------------------------
\vspace{-0.6\baselineskip}
Το πολύμετρο μετράει την αντίσταση του pt100 ή του θερμίστορ (χρωματισμός καλωδίων στο manual του CHP) και η μέτρηση διαβάζεται μέσω 'RS-232'.
Στο πολύμετρο πρέπει να είναι ενεργές οι επιλογές '*KEEP ON*' και '*RS232*'. Αυτό γίνεται με τα πλήκτρα 'menu' και 'enter' για κάθε μία από τις ρυθμίσεις.


\vspace{-1.05\baselineskip}
Εκκίνηση προγράμματος πολυμέτρου {-}
-------------------------------------
\vspace{-0.6\baselineskip}

Το πρόγραμμα (**protek506_measurments.py**) παίρνει μετρήσεις της αντίστασης - θερμοκρασίας του CHP1 και μπορεί να εκτελεστεί με όμοιο τρόπο με το πρόγραμμα του tracker.
Καθώς το πρόγραμμα παίρνει μετρήσεις, στη οθόνη του πολυμέτρου πρέπει να αναβοσβήνουν εναλλάξ οι ενδείξεις '*RX*' και '*TX*'.
Αν αυτό δεν γίνεται τότε η επικοινωνία έχει κολλήσει και το πολύμετρο πρέπει να κλείσει, να ξανανοίξει και να ρυθμιστεί (όπως παραπάνω).

\vspace{-1.05\baselineskip}
Σε περίπτωση διακοπής ρεύματος. {-}
------------------------------------
\vspace{-0.6\baselineskip}
Έχει παρατηρηθεί ότι ο tracker μπορεί να ξεκινήσει κανονικά όταν επανέλθει η τροφοδοσία και ξεκινήσει ο υπολογιστής. Αλλά αυτό δεν γίνεται πάντα.


\vspace{-1\baselineskip}
Scheduled script description {-}
---------------------------------
\vspace{-0.7\baselineskip}

Τα παρακάτω script εκτελούνται συνεχώς από το 'Task Scheduler' και σχετίζονται με τη καθημερινή λειτουργία του tracker και του CPH1, και είναι:

* **sun_tracker_main.py**       (απαραίτητο, ελέγχει την κίνηση του tracker)
* **protek506_measurments.py**  (σημαντικό, μετράει την θερμοκρασία του CPH1)
* **data_pub_win.py**           (βοηθητικό, εκπέμπει δεδομένα λειτουργίας του tracker)

**Σημείωση:** Σε περίπτωση που κάποιο από αυτά ήδη εκτελείται δεν θα ξανατρέξει, διότι υπάρχει εσωτερικός έλεγχος στον κώδικα του κάθε προγράμματος.

**Σημείωση:** Πρέπει να είναι είναι ενεργή η επιλογή: `"Disable error reporting"` ώστε να μην κολλάει ο tracker περιμένοντας τον διάλογο του "Error reporting" όταν crashάρει. Πιθανόν και η επιλογή `"But notify me when critical error occurs"` (υπό δοκιμή για την ώρα). Για *Windows XP: Control Panel > System > Advanced > Error reporting*.



# Tracker microcontroler source code

\tiny



```{r echo=F, include=T, eval=T, comment=NA, size="tiny",highlight='tango'}
cat(
readLines("/home/athan/Aerosols/borrowed source/Tracker LAP/Tracker v1.6.C"), sep = "\n"
)
```

\normalsize



